# Generated by Django 4.2.6 on 2023-10-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_address_remove_user_fname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='lname',
        ),
    ]
