# Generated by Django 4.2.6 on 2023-10-31 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.timezone)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
