# Generated by Django 4.2.6 on 2023-10-31 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_whishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whishlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
