# Generated by Django 4.2.6 on 2023-10-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_whishlist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
