# Generated by Django 4.2.6 on 2023-10-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_whishlist_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='whishlist',
            new_name='Wishlist',
        ),
    ]
